create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null unique,
  nombre text not null,
  rol text not null check (rol in ('SUPERVISOR', 'CAJERO')),
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.config (
  key text primary key,
  value text not null
);

create table if not exists public.marcas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.motos (
  id bigint generated by default as identity primary key,
  marca_id bigint references public.marcas(id),
  marca text not null,
  modelo text not null,
  tipo text,
  color text,
  chasis text not null unique,
  cilindrada text,
  motor text,
  precio numeric(12, 2) not null,
  precio_final numeric(12, 2) not null,
  descuento_maximo_pct numeric(5, 2) not null,
  cantidad_libre integer not null default 0,
  cantidad_reservada integer not null default 0,
  cantidad_vendida integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.accesorios (
  id bigint generated by default as identity primary key,
  marca_id bigint references public.marcas(id),
  marca text,
  tipo text not null,
  color text,
  precio numeric(12, 2) not null,
  precio_final numeric(12, 2) not null,
  descuento_maximo_pct numeric(5, 2) not null,
  cantidad_libre integer not null default 0,
  cantidad_reservada integer not null default 0,
  cantidad_vendida integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.repuestos (
  id bigint generated by default as identity primary key,
  marca_id bigint references public.marcas(id),
  marca text,
  tipo text not null,
  precio numeric(12, 2) not null,
  precio_final numeric(12, 2) not null,
  descuento_maximo_pct numeric(5, 2) not null,
  cantidad_libre integer not null default 0,
  cantidad_reservada integer not null default 0,
  cantidad_vendida integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table if not exists public.proformas (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  vendedor_id uuid not null references public.user_profiles(id),
  cliente_nombre text not null,
  cliente_ci_nit text not null,
  cliente_celular text not null,
  fecha_creacion timestamptz not null default now(),
  fecha_expiracion timestamptz not null,
  subtotal numeric(12, 2) not null default 0,
  total_descuentos numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  estado text not null default 'ACTIVA' check (estado in ('ACTIVA', 'VENCIDA', 'CONVERTIDA', 'CANCELADA')),
  notas text
);

create table if not exists public.proforma_items (
  id bigint generated by default as identity primary key,
  proforma_id bigint not null references public.proformas(id) on delete cascade,
  moto_id bigint references public.motos(id),
  accesorio_id bigint references public.accesorios(id),
  repuesto_id bigint references public.repuestos(id),
  descripcion text not null,
  modelo text,
  tipo text,
  color text,
  cilindrada text,
  motor text,
  precio_costo_snap numeric(12, 2) not null,
  precio_final_snap numeric(12, 2) not null,
  descuento_maximo_snap numeric(5, 2) not null,
  descuento_pct numeric(5, 2) not null,
  descuento_monto numeric(12, 2) not null,
  cantidad integer not null,
  precio_unitario_final numeric(12, 2) not null,
  subtotal numeric(12, 2) not null
);

create table if not exists public.ventas (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  proforma_id bigint references public.proformas(id),
  vendedor_id uuid not null references public.user_profiles(id),
  cliente_nombre text not null,
  cliente_ci_nit text not null,
  cliente_celular text not null,
  subtotal numeric(12, 2) not null,
  total_descuentos numeric(12, 2) not null,
  total numeric(12, 2) not null,
  estado text not null default 'COMPLETADA' check (estado in ('COMPLETADA', 'ANULADA')),
  notas text,
  fecha_venta timestamptz not null default now()
);

create table if not exists public.venta_items (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references public.ventas(id) on delete cascade,
  moto_id bigint references public.motos(id),
  accesorio_id bigint references public.accesorios(id),
  repuesto_id bigint references public.repuestos(id),
  descripcion text not null,
  precio_costo_snap numeric(12, 2) not null,
  precio_final_snap numeric(12, 2) not null,
  descuento_maximo_snap numeric(5, 2) not null,
  descuento_pct numeric(5, 2) not null,
  descuento_monto numeric(12, 2) not null,
  cantidad integer not null,
  precio_unitario_final numeric(12, 2) not null,
  subtotal numeric(12, 2) not null
);

create table if not exists public.tramites (
  id bigint generated by default as identity primary key,
  venta_item_id bigint not null references public.venta_items(id) on delete cascade,
  tipo text not null check (tipo in ('BSISA', 'PLACA')),
  nombre text not null,
  marca text,
  costo_total numeric(12, 2) not null,
  cobro_en_venta boolean not null,
  a_cuenta numeric(12, 2),
  saldo numeric(12, 2),
  estado text not null default 'PENDIENTE' check (estado in ('PENDIENTE', 'EN_PROCESO', 'COMPLETADO', 'CANCELADO')),
  observaciones text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz
);

create unique index if not exists uq_tramites_venta_item_tipo on public.tramites(venta_item_id, tipo);
create index if not exists idx_motos_activo on public.motos(activo);
create index if not exists idx_accesorios_activo on public.accesorios(activo);
create index if not exists idx_repuestos_activo on public.repuestos(activo);
create index if not exists idx_marcas_activo on public.marcas(activo);
create index if not exists idx_proformas_estado on public.proformas(estado);
create index if not exists idx_proformas_expiracion on public.proformas(fecha_expiracion);
create index if not exists idx_proforma_items_pf on public.proforma_items(proforma_id);
create index if not exists idx_ventas_fecha on public.ventas(fecha_venta);
create index if not exists idx_venta_items_venta on public.venta_items(venta_id);
create index if not exists idx_tramites_estado on public.tramites(estado);
create index if not exists idx_tramites_venta_item on public.tramites(venta_item_id);

insert into public.config(key, value)
values
  ('tramite_bsisa_costo', '0'),
  ('tramite_placa_costo', '0')
on conflict (key) do nothing;
