create table if not exists public.motos_e (
  id bigint generated by default as identity primary key,
  marca_id bigint references public.marcas(id),
  marca text not null,
  modelo text not null,
  tipo text,
  color text,
  chasis text not null unique,
  potencia text,
  motor text,
  precio numeric(12, 2) not null,
  precio_final numeric(12, 2) not null,
  descuento_maximo_pct numeric(5, 2) not null,
  cantidad_libre integer not null default 0,
  cantidad_reservada integer not null default 0,
  cantidad_vendida integer not null default 0,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create index if not exists idx_motos_e_activo on public.motos_e(activo);
create index if not exists idx_motos_e_busqueda on public.motos_e(marca, modelo, chasis);

alter table public.motos_e
  add constraint chk_motos_e_precio_valido check (precio >= 0 and precio_final >= 0 and precio_final >= precio),
  add constraint chk_motos_e_descuento_pct check (descuento_maximo_pct >= 0 and descuento_maximo_pct <= 100),
  add constraint chk_motos_e_stock_nonnegative check (
    cantidad_libre >= 0 and cantidad_reservada >= 0 and cantidad_vendida >= 0
  );

alter table public.motos_e enable row level security;

drop trigger if exists trg_motos_e_updated on public.motos_e;
create trigger trg_motos_e_updated
before update on public.motos_e
for each row execute function public.set_updated_timestamp();
