create table if not exists public.asignaciones_inventario (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  origen_punto_venta_id bigint not null references public.puntos_venta(id),
  destino_punto_venta_id bigint not null references public.puntos_venta(id),
  creado_por uuid not null references auth.users(id),
  estado text not null default 'PENDIENTE' check (estado in ('PENDIENTE','APLICADA','ANULADA')),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  aplicado_en timestamptz null
);

create table if not exists public.asignacion_inventario_items (
  id bigint generated by default as identity primary key,
  asignacion_id bigint not null references public.asignaciones_inventario(id) on delete cascade,
  producto_tipo text not null check (producto_tipo in ('motos','motos_e','accesorios','repuestos')),
  producto_id bigint not null,
  cantidad integer not null check (cantidad > 0),
  creado_en timestamptz not null default now()
);

create index if not exists idx_asignaciones_inventario_codigo on public.asignaciones_inventario(codigo);
create index if not exists idx_asignacion_items_lookup on public.asignacion_inventario_items(asignacion_id, producto_tipo, producto_id);

drop trigger if exists trg_asignaciones_inventario_updated on public.asignaciones_inventario;
create trigger trg_asignaciones_inventario_updated
before update on public.asignaciones_inventario
for each row execute function public.set_updated_timestamp();

create or replace function public.create_inventory_assignment(
  p_creado_por uuid,
  p_origen_punto_venta_id bigint,
  p_destino_punto_venta_id bigint,
  p_items jsonb
)
returns text
language plpgsql
as $$
declare
  v_codigo text;
  v_asignacion_id bigint;
  v_item jsonb;
  v_kind text;
  v_product_id bigint;
  v_cantidad integer;
begin
  if p_origen_punto_venta_id is null or p_destino_punto_venta_id is null then
    raise exception 'Origen y destino son requeridos';
  end if;
  if p_origen_punto_venta_id = p_destino_punto_venta_id then
    raise exception 'Origen y destino no pueden ser iguales';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Debe incluir al menos un item';
  end if;

  perform public.assert_active_point(p_origen_punto_venta_id);
  perform public.assert_active_point(p_destino_punto_venta_id);

  v_codigo := public.next_document_code('asignaciones_inventario', 'CON');

  insert into public.asignaciones_inventario (
    codigo,
    origen_punto_venta_id,
    destino_punto_venta_id,
    creado_por,
    estado
  ) values (
    v_codigo,
    p_origen_punto_venta_id,
    p_destino_punto_venta_id,
    p_creado_por,
    'PENDIENTE'
  )
  returning id into v_asignacion_id;

  for v_item in
    select value from jsonb_array_elements(p_items)
  loop
    v_kind := coalesce(v_item->>'kind', v_item->>'producto_tipo');
    v_product_id := (v_item->>'product_id')::bigint;
    if v_product_id is null then
      v_product_id := (v_item->>'producto_id')::bigint;
    end if;
    v_cantidad := greatest(coalesce((v_item->>'cantidad')::integer, 0), 0);

    if v_kind is null or v_kind not in ('motos','motos_e','accesorios','repuestos') then
      raise exception 'Tipo de producto invalido';
    end if;
    if v_product_id is null or v_product_id <= 0 then
      raise exception 'Producto invalido';
    end if;
    if v_cantidad <= 0 then
      raise exception 'Cantidad invalida';
    end if;

    insert into public.asignacion_inventario_items (
      asignacion_id,
      producto_tipo,
      producto_id,
      cantidad
    ) values (
      v_asignacion_id,
      v_kind,
      v_product_id,
      v_cantidad
    );
  end loop;

  return v_codigo;
end;
$$;

